# Generated by Django 5.1.6 on 2025-07-20 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('lock_comment', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.ugroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('multi_choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://cdn11.dienmaycholon.vn/filewebdmclnew/public/userupload/files/Image%20FP_2024/avatar-cute-54.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('USER', 'user'), ('USERPREMIUM', 'userpremium')], default='USER', max_length=15),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('notification_type', models.CharField(blank=True, choices=[('POSTGROUP', 'postgroup'), ('SYSTEM', 'system'), ('REACTION', 'reaction'), ('COMMENT', 'comment')], max_length=20, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPost',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='esocialnetworkapi.post')),
                ('end_time', models.DateTimeField()),
                ('survey_type', models.CharField(choices=[('MENTAL_HEALTH', 'Mental Health'), ('TRAINING_PROGRAM', 'Training Program'), ('RECRUITMENT_INFORMATION', 'Recruitment Info'), ('INCOME', 'Income'), ('EMPLOYMENT_SITUATION', 'Employment Situation')], max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('EXPIRED', 'expired')], default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('label', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.post')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drafted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.surveypost')),
            ],
            options={
                'unique_together': {('survey_post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_other_option', models.BooleanField(default=False)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.surveyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyDraftAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.TextField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.surveydraft')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.surveyoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.surveyquestion')),
            ],
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.surveypost'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('reaction', models.CharField(choices=[('LIKE', 'like'), ('HAHA', 'haha'), ('LOVE', 'love')], default='LIKE', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='UserSurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.TextField(blank=True, null=True)),
                ('survey_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esocialnetworkapi.surveyoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'survey_option')},
            },
        ),
    ]
