# Generated by Django 5.1.6 on 2025-07-23 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0003_alter_comment_image_alter_postimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
