# Generated by Django 5.1.6 on 2025-07-23 09:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0004_ugroup_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugroup',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVs1Lq3x9vC32Bs_M77R8FJj1nMlgyhSKkCg&s', max_length=255, verbose_name='avatar'),
        ),
    ]
