# Generated by Django 5.1.6 on 2025-07-29 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0006_alter_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
