# Generated by Django 5.1.6 on 2025-08-05 09:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0007_postimage_active_postimage_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ugroup',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVs1Lq3x9vC32Bs_M77R8FJj1nMlgyhSKkCg&s', max_length=255, verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='ugroup',
            name='introduce',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ugroup',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ugroup',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ugroup',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ugroup',
            name='rule',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ugroup',
            name='type',
            field=models.CharField(choices=[('support', 'Hỗ trợ tâm lý'), ('research', 'Nghiên cứu khoa học'), ('sharing', 'Chia sẻ - Tâm sự'), ('therapy', 'Trị liệu')], default='support', max_length=50),
        ),
        migrations.AddField(
            model_name='ugroup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='groups', to='esocialnetworkapi.tag'),
        ),
    ]
