# Generated by Django 5.1.6 on 2025-08-05 09:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0008_tag_ugroup_cover_ugroup_introduce_ugroup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugroup',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='v1753776324/gmrkdeularqtqhqidc4g.jpg', max_length=255, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='ugroup',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='v1753776324/gmrkdeularqtqhqidc4g.jpg', max_length=255, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='v1753776324/gmrkdeularqtqhqidc4g.jpg', max_length=255, verbose_name='avatar'),
        ),
    ]
