# Generated by Django 5.1.6 on 2025-08-05 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0009_alter_ugroup_avatar_alter_ugroup_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='esocialnetworkapi.post')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post', to='esocialnetworkapi.ugroup')),
            ],
        ),
    ]
