# Generated by Django 5.1.6 on 2025-08-05 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0010_remove_post_group_grouppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugroup',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
