# Generated by Django 5.1.6 on 2025-08-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0011_ugroup_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupUser',
        ),
    ]
