# Generated by Django 5.1.6 on 2025-09-02 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0013_threadroom_contact_threadroomparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='ugroup',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('POSTGROUP', 'postgroup'), ('SYSTEM', 'system'), ('REACTION', 'reaction'), ('COMMENT', 'comment'), ('CONTACT', 'contact')], max_length=20, null=True),
        ),
    ]
