# Generated by Django 5.1.6 on 2025-09-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocialnetworkapi', '0014_alter_post_options_alter_ugroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveypost',
            name='survey_type',
            field=models.CharField(choices=[('MENTAL_HEALTH', 'Mental Health'), ('HANDLE_SITUATION', 'Handle situation'), ('RECRUITMENT_INFO', 'Recruitment Info'), ('INCOME', 'Income')], max_length=30),
        ),
    ]
